accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_user, name='logout'),
]

homepage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

library/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='library'),
    path('data/', views.data, name='library-data'),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('library/', include('library.urls')),
    path('user/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.


class Status(models.Model):
    status = models.CharField(max_length=300)
    submit_time = models.DateTimeField(auto_now_add=True)

library/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import forms


class CreateStatus(forms.Form):
    status = forms.CharField(max_length=300)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # log the user in
            return redirect('accounts:login')
    else:
        form = UserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'signup.html', context)


def login_user(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log in user
            user = form.get_user()
            login(request, user)
            return redirect('accounts:login')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    return redirect('accounts:login')

homepage/views.py
from django.shortcuts import render, redirect
from .models import Status
from .forms import CreateStatus

# Create your views here.


def index(request):
    if request.method == 'POST':
        form = CreateStatus(request.POST)
        if form.is_valid():
            stat = Status(
                status=form.data["status"],
            )
            stat.save()

    else:
        form = CreateStatus()

    statuses = Status.objects.all()

    context = {
        'form': form,
        'statuses': statuses,
    }
    return render(request, 'index.html', context)

library/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json


def index(request):
    return render(request, 'library.html')


def data(request):
    try:
        q = request.GET['q']

    except:
        q = 'quilting'

    json_read = requests.get(
        'https://www.googleapis.com/books/v1/volumes?q=' + q).json()
    return JsonResponse(json_read)

accounts/templates/login.html
<!DOCTYPE html>
<html lang="en">
{% load static %}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Library</title>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i&display=swap"
        rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="{% static 'css/auth.css' %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>


</head>

<body data-theme="default">
    <div class="content-container">

        {% if user.is_authenticated == False %}

        <h1>Log In</h1>

        <form method="POST" action="{% url 'accounts:login' %}">
            {% csrf_token %}
            <table>
                {{ form }}
            </table>
            <button type="submit" name="loginbtn">Log In</button>
        </form>

        <p>Don't have an account yet?<a href="{% url 'accounts:signup' %}">Sign Up here</a></span></p>

        {% else %}

        <h1 class="">Welcome back, {{request.user.username}}</h1>
        <p>You are logged in</p>
        <form action="{% url 'accounts:logout' %}">
            <button type="submit" name="logoutbtn">Log out</button>
        </form>

        {% endif %}


        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"> </script>
        <script src="{% static 'js/library.js' %}"></script>

</body>

</html>

accounts/templates/signup.html
<!DOCTYPE html>
<html lang="en">
{% load static %}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up</title>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i&display=swap"
        rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="{% static 'css/auth.css' %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>


</head>

<body data-theme="default">
    <div class="content-container">

        <h1>Sign Up</h1>

        <form method="POST" action="/user/signup/">
            {% csrf_token %}
            {{ form }}

            <button type="submit" class="button" name="signupbtn">Sign Up</button>
        </form>

        <p>Already have an account? <span><a href="{% url 'accounts:login' %}">Log In</a></span></p>


        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"> </script>
        <script src="{% static 'js/library.js' %}"></script>

</body>

</html>

homepage/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Halo, Apa Kabar?</title>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i&display=swap"
        rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>

<body data-theme="default">
    <div class="content-container">
        <div class="color-scheme-container">
            <div class="color-scheme" id="green"></div>
            <div class="color-scheme" id="white"></div>
            <div class="color-scheme" id="black"></div>
        </div>

        <h1>Tiny Bits About Me.</h1>
        <p style="padding: 24px">Here's a little glimpse of what I do as a regular CS student</p>
        <div class="accordion-container">
            <ul class="accordion">
                <li>
                    <h3 class="toggle" id="accordion-1">Activities</h3>
                    <div class="inner">
                        <p>I code</p>
                    </div>
                </li>
                <li>
                    <h3 class="toggle" id="accordion-2">Organization</h3>
                    <div class="inner">
                        <p>IT Force FUKI</p>
                        <p>Educare 2020</p>
                    </div>
                </li>
                <li>
                    <h3 class="toggle" id="accordion-3">Achievement</h3>
                    <div class="inner">
                        <p>Surviving pacil</p>
                    </div>
                </li>
            </ul>
        </div>

        <h1>Halo, apa kabar?</h1>
        <p style="padding: 24px; padding-bottom: 0">How are you, <b>really</b>?</p>
        <form method="POST">
            {% csrf_token %}
            <input type="text" name="status" id="id_status" maxlength="300" required>
            <button type="submit" name="submit">Submit</button>
        </form>

        <div class="status-container">
            {% for status in statuses %}
            <div class="status-card">
                <p>{{ status.submit_time|date:"d M Y" }} {{ status.submit_time|time:"H:i"}}</p>
                <p><b>{{ status.status }}</b></p>
            </div>
            {% endfor %}
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"> </script>
    <script src="{% static 'index.js' %}"></script>
</body>

</html>

library/templates/library.html
<!DOCTYPE html>
<html lang="en">
{% load static %}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Library</title>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i&display=swap"
        rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="{% static 'css/librarypage.css' %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>


</head>

<body data-theme="default">
    <div class="content-container">

        <h1>Digital Library.</h1>

        <p>Looking for books to read?</p>
        <div class="search-container">
            <input type="text" name="book-input" id="book-input" maxlength="300" placeholder="Search for books"
                title="Type in the title, author or publisher.">
            <button type="submit" name="search-button" id="search-button">Search</button>
        </div>
        <table id="books-table" class="table table-borderless table-dark">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Cover</th>
                    <th>Title</th>
                    <th>Authors</th>
                    <th>Publisher</th>
                    <th>Published Date</th>
                </tr>
            </thead>
            <tbody id="table-content"></tbody>
        </table>




        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"> </script>
        <script src="{% static 'js/library.js' %}"></script>

</body>

</html>